apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wholo.fullname" . }}-api
  labels:
    app: {{ include "wholo.fullname" . }}-api
type: Opaque
stringData:
  DATABASE_URL: {{ include "wholo.postgresql.url" . | quote }}
  JWT_SECRET: {{ .Values.api.jwt.secret | quote }}
  R2_ACCESS_KEY_ID: {{ .Values.api.r2.accessKeyId | quote }}
  R2_SECRET_ACCESS_KEY: {{ .Values.api.r2.secretAccessKey | quote }}
