apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wholo.fullname" . }}-portal-api
  labels:
    app: {{ include "wholo.fullname" . }}-portal-api
data:
  PORT: "3003"
  NODE_ENV: "production"
  JWT_EXPIRES_IN: {{ .Values.portalApi.jwt.expiresIn | quote }}
  CENTRAL_API_URL: {{ .Values.portalApi.centralApiUrl | quote }}
