apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wholo.fullname" . }}-portal-api
  labels:
    app: {{ include "wholo.fullname" . }}-portal-api
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.portalApi.jwt.secret | quote }}
