apiVersion: v1
kind: Service
metadata:
  name: {{ include "wholo.fullname" . }}-portal-api
  labels:
    app: {{ include "wholo.fullname" . }}-portal-api
spec:
  type: {{ .Values.portalApi.service.type }}
  selector:
    app: {{ include "wholo.fullname" . }}-portal-api
  ports:
    - name: http
      port: {{ .Values.portalApi.service.port }}
      targetPort: 3010
