apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wholo.fullname" . }}-driver-api
  labels:
    app: {{ include "wholo.fullname" . }}-driver-api
data:
  PORT: "3030"
  NODE_ENV: "production"
  CENTRAL_API_URL: {{ .Values.driverApi.centralApiUrl | quote }}
  NEXT_APP_DIR: "/app/driver"
