apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wholo.fullname" . }}-keycloak
  labels:
    app: {{ include "wholo.fullname" . }}-keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.adminUser | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | quote }}
  KC_DB_PASSWORD: {{ .Values.postgresql.password | quote }}
