apiVersion: v1
kind: Service
metadata:
  name: {{ include "wholo.fullname" . }}-keycloak
  labels:
    app: {{ include "wholo.fullname" . }}-keycloak
spec:
  type: {{ .Values.keycloak.service.type | default "LoadBalancer" }}
  selector:
    app: {{ include "wholo.fullname" . }}-keycloak
  ports:
    - port: {{ .Values.keycloak.port }}
      targetPort: 8080
