apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wholo.fullname" . }}-postgresql
  labels:
    app: {{ include "wholo.fullname" . }}-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.postgresql.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize }}
