apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wholo.fullname" . }}-postgresql
  labels:
    app: {{ include "wholo.fullname" . }}-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize }}
