apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wholo.fullname" . }}-postgresql
  labels:
    app: {{ include "wholo.fullname" . }}-postgresql
type: Opaque
stringData:
  password: {{ .Values.postgresql.password | quote }}
  url: {{ include "wholo.postgresql.url" . | quote }}
