{{- if .Values.influxdb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wholo.fullname" . }}-influxdb
  labels:
    app: {{ include "wholo.fullname" . }}-influxdb
type: Opaque
stringData:
  INFLUXDB_ADMIN_PASSWORD: {{ required "influxdb.adminPassword is required when influxdb.enabled" .Values.influxdb.adminPassword | quote }}
  INFLUXDB_ADMIN_TOKEN: {{ required "influxdb.adminToken is required when influxdb.enabled" .Values.influxdb.adminToken | quote }}
{{- end }}
