{{- if .Values.plausible.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wholo.fullname" . }}-clickhouse
  labels:
    app: {{ include "wholo.fullname" . }}-clickhouse
spec:
  type: ClusterIP
  selector:
    app: {{ include "wholo.fullname" . }}-clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
{{- end }}
