apiVersion: v1
kind: Service
metadata:
  name: {{ include "wholo.fullname" . }}-www
  labels:
    app: {{ include "wholo.fullname" . }}-www
spec:
  type: {{ .Values.www.service.type }}
  selector:
    app: {{ include "wholo.fullname" . }}-www
  ports:
    - name: http
      port: {{ .Values.www.service.port }}
      targetPort: 3040
