apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wholo.fullname" . }}-redis
  labels:
    app: {{ include "wholo.fullname" . }}-redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storageSize }}
