apiVersion: v1
kind: Service
metadata:
  name: {{ include "wholo.fullname" . }}-redis
  labels:
    app: {{ include "wholo.fullname" . }}-redis
spec:
  selector:
    app: {{ include "wholo.fullname" . }}-redis
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: 6379
