{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wholo.fullname" . }}
  labels:
    app: {{ include "wholo.fullname" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        {{- if .Values.ingress.hosts.portal }}
        - {{ .Values.ingress.hosts.portal | quote }}
        {{- end }}
        {{- if .Values.ingress.hosts.admin }}
        - {{ .Values.ingress.hosts.admin | quote }}
        {{- end }}
        {{- if .Values.ingress.hosts.api }}
        - {{ .Values.ingress.hosts.api | quote }}
        {{- end }}
        {{- if .Values.ingress.hosts.auth }}
        - {{ .Values.ingress.hosts.auth | quote }}
        {{- end }}
      secretName: {{ include "wholo.fullname" . }}-tls
  rules:
    {{- if .Values.ingress.hosts.portal }}
    - host: {{ .Values.ingress.hosts.portal | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "wholo.fullname" . }}-portal-api
                port:
                  number: {{ .Values.portalApi.service.port }}
    {{- end }}
    {{- if .Values.ingress.hosts.admin }}
    - host: {{ .Values.ingress.hosts.admin | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "wholo.fullname" . }}-admin-api
                port:
                  number: {{ .Values.adminApi.service.port }}
    {{- end }}
    {{- if .Values.ingress.hosts.api }}
    - host: {{ .Values.ingress.hosts.api | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "wholo.fullname" . }}-api
                port:
                  number: {{ .Values.api.service.port }}
    {{- end }}
    {{- if .Values.ingress.hosts.auth }}
    - host: {{ .Values.ingress.hosts.auth | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "wholo.fullname" . }}-keycloak
                port:
                  number: {{ .Values.keycloak.port }}
    {{- end }}
{{- end }}
