apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wholo.fullname" . }}-admin-api
  labels:
    app: {{ include "wholo.fullname" . }}-admin-api
data:
  PORT: "3002"
  NODE_ENV: "production"
  REDIS_URL: {{ printf "redis://%s:%d" (include "wholo.redis.host" .) (int .Values.redis.port) | quote }}
  CENTRAL_API_URL: {{ .Values.adminApi.centralApiUrl | quote }}
  KEYCLOAK_URL: {{ printf "http://%s:%d" (include "wholo.keycloak.host" .) (int .Values.keycloak.port) | quote }}
  KEYCLOAK_REALM: {{ .Values.keycloak.realm | quote }}
